[workspace]
resolver = "2"
members = [
    "cmd/soroban-cli",
    "cmd/crates/*",
    "cmd/crates/soroban-test/tests/fixtures/test-wasms/*",
    "cmd/crates/soroban-test/tests/fixtures/hello",
    "cmd/soroban-rpc/lib/preflight",
]
default-members = ["cmd/soroban-cli", "cmd/crates/soroban-test"]
exclude = ["cmd/crates/soroban-test/tests/fixtures/hello"]

[workspace.package]
version = "0.8.5"

[workspace.dependencies.soroban-env-host]
version = "0.0.16"
git = "https://github.com/stellar/rs-soroban-env"
rev = "c43bbd47959dde2e39eeeb5b7207868a44e96c7d"

[workspace.dependencies.soroban-spec]
version = "0.8.4"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "56bf97576eb045e34655a30277bcbfd480df62d2"
# path = "../rs-soroban-sdk/soroban-spec"

[workspace.dependencies.soroban-spec-typescript]
version = "0.8.5"
path = "./cmd/crates/soroban-spec-typescript"

[workspace.dependencies.soroban-spec-tools]
version = "0.8.5"
path = "./cmd/crates/soroban-spec-tools"

[workspace.dependencies.soroban-sdk]
version = "0.8.4"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "4c9bdc23d89913a6ab4c10b2bbe45f4d3a1939d2"

[workspace.dependencies.soroban-ledger-snapshot]
version = "0.8.4"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "4c9bdc23d89913a6ab4c10b2bbe45f4d3a1939d2"

[workspace.dependencies.soroban-cli]
version = "0.8.5"
path = "cmd/soroban-cli"

[workspace.dependencies.stellar-xdr]
version = "0.0.16"
git = "https://github.com/stellar/rs-stellar-xdr"
rev = "50c7a57e55603bc57719b1d096091b3239ea6859"
default-features = false

[workspace.dependencies]
base64 = "0.13.0"
ethnum = "1.3.2"
hex = "0.4.3"
itertools = "0.10.0"
sep5 = "0.0.2"
serde_json = "1.0.82"
serde = "1.0.82"
stellar-strkey = "0.0.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-appender = "0.2.2"
which = "4.4.0"
wasmparser = "0.90.0"


# [patch."https://github.com/stellar/rs-soroban-env"]
# soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }
# [patch."https://github.com/stellar/rs-soroban-sdk"]
# soroban-spec = { path = "../rs-soroban-sdk/soroban-spec/" }
# soroban-token-spec = { path = "../rs-soroban-sdk/soroban-token-spec/" }
# soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk/" }
# [patch."https://github.com/stellar/rs-stellar-xdr"]
# stellar-xdr = { path = "../rs-stellar-xdr/" }

[profile.test-wasms]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-panic-unwind]
inherits = 'release'
panic = 'unwind'
